### ISSUE TITLE
哎，做好事做到底，不能直接给个连接粘到 vultr 就能上传吗？

### ISSUE THREAD

**Issue by GF-Huang** [ILLKX/Windows-VirtIO#1]

**Comment by ILLKX** [comment]
兄啊，直链要服务器的啊，服务器要带宽的啊，今天commit完不到5分钟，所有链接被Google限流了，这是我一个小人物能承受的起的下载量？推荐转存以后用Google直链提取就行了

**Comment by GF-Huang** [comment]
请问如何直连提取？

**Comment by ILLKX** [comment]
https://yutuo.net/archives/dded2c8acd8d02de.html

**Comment by GF-Huang** [comment]
好，谢谢
