### ISSUE TITLE
请问VitrIO的驱动放在哪里目录了？

### ISSUE THREAD

**Issue by sidianhao** [ILLKX/Windows-VirtIO#4]
RT.
Thanks

**Comment by flydream3618** [comment]
> RT. Thanks

如果你看不到Virtio目录，说明楼主逗你玩哈，自己加吧

**Comment by pcvc** [comment]
确实找不到Virtio目录

**Comment by ILLKX** [comment]
https://blog.mydns.vip/1828.html

For your reference.
